# MarketCheck Listings Samples
- Listings
- NeoVIN

## Environment

In [189]:
# packages
import numpy as np
import pandas as pd

In [190]:
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_colwidth', 50)

## Load Listings

In [191]:
# listings data
df = pd.read_csv('data/marketcheck_listings_sample.csv',low_memory=False)
print(df.shape)

(10000, 86)

In [192]:
# drop duplicates by vin
print(df.shape)
df.drop_duplicates(subset = 'vin',inplace=True)
print(df.shape)

(10000, 86)
(10000, 86)

In [193]:
df.columns

Index(['id', 'vin', 'heading', 'more_info', 'price', 'msrp', 'miles',
       'stock_no', 'year', 'make', 'model', 'trim', 'vehicle_type',
       'body_type', 'body_subtype', 'drivetrain', 'fuel_type', 'engine',
       'engine_block', 'engine_size', 'engine_measure', 'engine_aspiration',
       'transmission', 'speeds', 'doors', 'cylinders', 'city_mpg',
       'highway_mpg', 'interior_color', 'exterior_color',
       'base_exterior_color', 'base_interior_color', 'is_certified',
       'is_transfer', 'taxonomy_vin', 'model_code', 'scraped_at',
       'status_date', 'first_scraped_at', 'dealer_id', 'source', 'seller_name',
       'street', 'city', 'state', 'zip', 'latitude', 'longitude', 'country',
       'seller_phone', 'seller_email', 'seller_type', 'listing_type',
       'inventory_type', 'dealer_type', 'car_seller_name', 'car_address',
       'car_street', 'car_city', 'car_state', 'car_zip', 'car_latitude',
       'car_longitude', 'seller_comments', 'options', 'features',
       'photo_links', 'photo_url', 'dom', 'dom_180', 'dom_active',
       'currency_indicator', 'miles_indicator', 'carfax_1_owner',
       'carfax_clean_title', 'loan_term', 'loan_apr', 'l_down_pay', 'l_emi',
       'f_down_pay', 'f_down_pay_per', 'f_emi', 'lease_term', 'in_transit',
       'in_transit_at', 'in_transit_days'],
      dtype='object')

In [194]:
df = df[['vin', 'price', 'miles',
       'year', 'make', 'model', 'trim', 'vehicle_type',
       'body_type', 'body_subtype', 'drivetrain', 'fuel_type', 'engine',
       'engine_block', 'engine_size',
       'transmission', 'speeds', 'doors', 'cylinders', 'city_mpg',
       'highway_mpg',
       'base_exterior_color', 'base_interior_color', 'is_certified',
       'scraped_at',
       'status_date', 'first_scraped_at',
       'city', 'state', 'zip', 'latitude', 'longitude',
       'seller_type',
       'inventory_type', 'dealer_type',
       'seller_comments', 'options', 'features',
       'dom', 'dom_180', 'dom_active',
       'miles_indicator', 'carfax_1_owner',
       'carfax_clean_title','loan_apr'
       ]]

In [195]:
pd.DataFrame(df.nunique()).T

,vin,price,miles,year,make,model,trim,vehicle_type,body_type,body_subtype,drivetrain,fuel_type,engine,engine_block,engine_size,transmission,speeds,doors,cylinders,city_mpg,highway_mpg,base_exterior_color,base_interior_color,is_certified,scraped_at,status_date,first_scraped_at,city,state,zip,latitude,longitude,seller_type,inventory_type,dealer_type,seller_comments,options,features,dom,dom_180,dom_active,miles_indicator,carfax_1_owner,carfax_clean_title,loan_apr
0,10000,4342,9358,42,52,624,715,2,18,4,3,14,111,3,52,3,0,4,7,83,71,13,13,1,9960,9269,9989,2402,53,3913,6620,6625,1,1,2,6025,3074,6340,979,756,702,2,2,2,123

In [196]:
df.sample(5).T

,3002,9403,2343,199,6695
vin,1FTEW1EFXHFA56544,SHHFK8G73LU201031,1FAHP2F84EG131492,1FM5K8DH8HGB83998,3VV2B7AX3JM176922
price,30800.0,41488.0,20995.0,23650.0,25998.0
miles,100825.0,48760.0,0.0,85765.0,45668.0
year,2017.0,2020.0,2014.0,2017.0,2018.0
make,Ford,Honda,Ford,Ford,Volkswagen
model,F-150,Civic Hatchback,Taurus,Explorer,Tiguan
trim,XLT,Type-R,Limited,XLT,SE
vehicle_type,Truck,NaN,NaN,Truck,Truck
body_type,Pickup,Hatchback,Sedan,SUV,SUV
body_subtype,Crew,NaN,NaN,NaN,NaN
drivetrain,4WD,FWD,FWD,4WD,4WD
fuel_type,E85 / Unleaded,Premium Unleaded,E85 / Unleaded,Premium Unleaded,Unleaded
engine,5.0L V8,2.0L I4,3.5L V6,2.3L I4,2.0L I4
engine_block,V,NaN,NaN,I,I
engine_size,5.0,NaN,NaN,2.3,2.0
transmission,Automatic,Manual,Automatic,Automatic,Automatic
speeds,NaN,NaN,NaN,NaN,NaN
doors,4.0,5.0,4.0,5.0,5.0
cylinders,8.0,NaN,NaN,4.0,4.0
city_mpg,18.0,29.0,22.0,19.0,21.0
highway_mpg,23.0,37.0,32.0,27.0,27.0
base_exterior_color,Silver,Blue,Black,White,White
base_interior_color,Gray,Black,NaN,NaN,Brown
is_certified,NaN,NaN,NaN,NaN,NaN
scraped_at,2022-09-29T22:39:04Z,2022-10-03T16:12:21Z,2022-09-10T22:53:22Z,2022-10-06T19:57:49Z,2022-10-01T19:39:30Z
status_date,2022-10-09T22:37:13Z,2022-10-09T18:14:58Z,2022-10-09T21:05:12Z,2022-10-09T19:58:09Z,2022-10-09T19:42:40Z
first_scraped_at,2020-04-18T19:44:26Z,2022-06-11T18:59:17Z,2014-12-22T01:27:28Z,2018-03-09T22:02:40Z,2018-08-18T14:25:41Z
city,Thomson,Placentia,Kansas City,Clio,Murrieta
state,GA,CA,MO,MI,CA
zip,30824,92870,64114,48420,92562
latitude,33.514806,33.861079,38.984728,43.176708,33.550894
longitude,-82.501592,-117.879795,-94.594308,-83.763174,-117.190903
seller_type,dealer,dealer,dealer,dealer,dealer
inventory_type,used,used,used,used,used
dealer_type,franchise,independent,independent,franchise,independent
seller_comments,Clean CARFAX.Thomson Chrysler Dodge Jeep Ram F...,$487.83 Per Month - On Approved Credit* See ou...,NaN,3 DAY EXCHANGE POLICY!! 2017 Ford Explorer XLT...,NaN
options,NaN,NaN,NaN,6 Speakers|AM/FM radio: SiriusXM|Radio: AM/FM ...,NaN
features,AWD|Fog Lights|Heated Seats|Keyless Entry|Remo...,(Backup Camera. Bluetooth)|Auto On/Off Aero-Co...,Automatic Climate Control|Keyless Entry|Parkin...,"3.65 Axle Ratio|GVWR: 6,160 lbs|Automatic Full...",Traction Control|Leatherette Seats|Power Mirro...
dom,83,121,31,115,210
dom_180,12,121,30,93,55
dom_active,12,121,30,93,55
miles_indicator,MILES,MILES,MILES,MILES,MILES
carfax_1_owner,0.0,1.0,0.0,0.0,NaN
carfax_clean_title,1.0,0.0,0.0,1.0,NaN
loan_apr,0.0,0.0,0.0,NaN,0.0

## Missingness

In [197]:
df.sample(2)

,vin,price,miles,year,make,model,trim,vehicle_type,body_type,body_subtype,drivetrain,fuel_type,engine,engine_block,engine_size,transmission,speeds,doors,cylinders,city_mpg,highway_mpg,base_exterior_color,base_interior_color,is_certified,scraped_at,status_date,first_scraped_at,city,state,zip,latitude,longitude,seller_type,inventory_type,dealer_type,seller_comments,options,features,dom,dom_180,dom_active,miles_indicator,carfax_1_owner,carfax_clean_title,loan_apr
3794,1GCUYDED6KZ295360,46597.0,10777.0,2019.0,Chevrolet,Silverado 1500,LT,NaN,Pickup,Crew,4WD,Unleaded,5.3L V8,NaN,NaN,Automatic,NaN,4.0,NaN,19.0,22.0,Gray,Black,1.0,2022-09-05T22:50:46Z,2022-10-09T23:05:56Z,2022-03-17T22:25:20Z,Richmond,IN,47374,39.832116,-84.83740,dealer,used,franchise,"To schedule a VIP appointment, please contact ...",NaN,AWD|Android Auto|Apple CarPlay|Bluetooth|Side-...,207,207,207,MILES,1.0,0.0,0.0
6617,3N1CP5CV7LL510367,22287.0,12022.0,2020.0,Nissan,Kicks,SV,Truck,SUV,NaN,FWD,Unleaded,1.6L I4,I,1.6,CVT,NaN,5.0,4.0,31.0,36.0,White,Gray,NaN,2022-09-30T20:51:07Z,2022-10-09T21:22:34Z,2020-03-19T18:11:06Z,Tempe,AZ,85281,33.439454,-111.92187,dealer,used,independent,"for 2020 Nissan Kicks SV SUVfor sale in Tempe,...",NaN,Air Conditioning|Back-Up Camera|Bluetooth Conn...,442,270,270,MILES,0.0,0.0,0.0

In [ ]:
# not being used with simple imputer
fillna_dict = {
'vin' :                    'Unknown'
,'price' :                 -1
,'miles' :                 -1
,'year' :                  -1
,'make' :                   'Unknown'
,'model' :                  'Unknown'
,'trim' :                  'Unknown'
,'vehicle_type' :           'Unknown'
,'body_type' :              'Unknown'
,'body_subtype' :           'Unknown'
,'drivetrain' :             'Unknown'
,'fuel_type' :              'Unknown'
,'engine' :                 'Unknown'
,'engine_block' :           'Unknown'
,'engine_size' :           -1
,'transmission' :           'Unknown'
,'speeds' :                -1
,'doors' :                 -1
,'cylinders' :             -1
,'city_mpg' :              -1
,'highway_mpg' :           -1
,'base_exterior_color' :    'Unknown'
,'base_interior_color' :    'Unknown'
,'is_certified' :          -1
,'scraped_at' :             'Unknown'
,'status_date' :            'Unknown'
,'first_scraped_at' :       'Unknown'
,'city' :                   'Unknown'
,'state' :                  'Unknown'
,'zip' :                     -1
,'latitude' :              -1
,'longitude' :             -1
,'seller_type' :            'Unknown'
,'inventory_type' :         'Unknown'
,'dealer_type' :            'Unknown'
,'seller_comments' :        'Unknown'
,'options' :                'Unknown'
,'features' :               'Unknown'
,'dom' :                     -1
,'dom_180' :                 -1
,'dom_active' :              -1
,'miles_indicator' :        'Unknown'
,'carfax_1_owner' :        -1
,'carfax_clean_title' :    -1
,'loan_apr' :              -1}

In [198]:
df.dtypes

vin                     object
price                  float64
miles                  float64
year                   float64
make                    object
model                   object
trim                    object
vehicle_type            object
body_type               object
body_subtype            object
drivetrain              object
fuel_type               object
engine                  object
engine_block            object
engine_size            float64
transmission            object
speeds                 float64
doors                  float64
cylinders              float64
city_mpg               float64
highway_mpg            float64
base_exterior_color     object
base_interior_color     object
is_certified           float64
scraped_at              object
status_date             object
first_scraped_at        object
city                    object
state                   object
zip                      int64
latitude               float64
longitude              float64
seller_type             object
inventory_type          object
dealer_type             object
seller_comments         object
options                 object
features                object
dom                      int64
dom_180                  int64
dom_active               int64
miles_indicator         object
carfax_1_owner         float64
carfax_clean_title     float64
loan_apr               float64
dtype: object

In [199]:
cols = df.columns

In [203]:
from sklearn.impute import SimpleImputer
imp_fill = SimpleImputer(missing_values=pd.NA, strategy='constant',fill_value=None) # fill_value='missing_value' / 0
df = pd.DataFrame(imp_fill.fit_transform(df), columns=cols)

In [205]:
df.dtypes

vin                    object
price                  object
miles                  object
year                   object
make                   object
model                  object
trim                   object
vehicle_type           object
body_type              object
body_subtype           object
drivetrain             object
fuel_type              object
engine                 object
engine_block           object
engine_size            object
transmission           object
speeds                 object
doors                  object
cylinders              object
city_mpg               object
highway_mpg            object
base_exterior_color    object
base_interior_color    object
is_certified           object
scraped_at             object
status_date            object
first_scraped_at       object
city                   object
state                  object
zip                    object
latitude               object
longitude              object
seller_type            object
inventory_type         object
dealer_type            object
seller_comments        object
options                object
features               object
dom                    object
dom_180                object
dom_active             object
miles_indicator        object
carfax_1_owner         object
carfax_clean_title     object
loan_apr               object
dtype: object

## Write Out

In [204]:
df.to_parquet('data/marketcheck_listings_sample_clean.parquet',index=False)

ArrowInvalid: ("Could not convert 'missing_value' with type str: tried to convert to double", 'Conversion failed for column price with type object')